spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 服务名称尽量用-,不要用下划线或者特殊字符
    name: user-center
server:
  port: 8081