spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos 的server地址
        server-addr: localhost:8848
        # 自己定义元数据
        cluster-name: NJ
    #        metadata:
    #          instance: c
    #          haha: hehe
    #          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          #如果用的是RocketMQ，一定要设置
          #如果用的是其他MQ，可留空,
          group: binder-group
        my-input:
          destination: add-bonus
          group: binder-group
  application:
    # 服务名称尽量用-不要用下划线或者特殊字符
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
server:
  port: 8081