spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/content_center
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 服务名称尽量用-不要用下划线或者特殊字符
    name: content-center
server:
  port: 8010
management:
  endpoints:
    web:
      #暴露所有的监控端点
      exposure:
        include: '*'