spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 服务名称尽量用-,不要用下划线(_)或者特殊字符
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: NJ
server:
  port: 8081