spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos 的server地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #指定Sentinel控制台的地址
        dashboard: localhost:8080
      filter:
        #新版本1.7.1不配置这个属性在控制台只会显示/**而不是显示访问的端点
        #https://github.com/alibaba/Sentinel/issues/1318
        url-patterns: /**
    stream:
      rocketmq:
        binder:
          name-server: 192.168.1.130:9876
  application:
    # 服务名称尽量用-不要用下划线或者特殊字符
    name: content-center
server:
  port: 8010
management:
  endpoints:
    web:
      #暴露所有的监控端点
      exposure:
        include: '*'
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 想要调用的微服务的名称
      user-center:
        loggerLevel: full #日志级别
  httpclient:
    #让Feign使用HttpClient做请求
    enabled: true
    #Feign的最大连接数
    max-connections: 200
    #Feign的单个连接的最大连接数
    max-connections-per-route: 50
  sentinel:
    enabled: true
rocketmq:
  name-server: 192.168.1.130:9876
  producer:
    #小坑，必须指定group
    group: test-group